# 1.python基础试题

1.1 python 中boolean、float 和 int 分别表示什么？

三者都代表类型tpye boolean是布尔型，返回True或False float是浮点型，代表有小数点的数，可以为正或负数 int是整数型，代表整数，可以为正或负数

1.2  设计求1-2+3-4+5 ... 99的所有数的和

In [1]:
a=0
b=0
for n in range(1,101,2):
    a+=n
for m in range(0,100,2):
    b+=m
print(a-b)

50


1.3  将字符串 s="yoyo" 转换成列表

In [2]:
s="yoyo"
s=[s[0],s[1],s[2],s[3]]
s

['y', 'o', 'y', 'o']

# 2. python进阶基础试题

2.1     for i in range(1,100)[2::3][-10:]: 

                print i 
                
        理解这段代码，并说出它是如何取数的

for循环；（1，100）指依次取1到99的数；[2::3]指从第3行开始到99间隔为3的数；[-10:]指取最后10个数

2.2 使用init 实例化时自动运行  分别计算单只股票最高价和收盘价两个时间点差值问题,可统一为one、two两个时间点,其最高价和收盘价赋值为 one(15,7) two(66,20)

In [3]:
class StockA:
    def __init__(self,diff,high,close):
        self.diff=diff
        self.high=high
        self.close=close
    def dif(self):
        return {self.diff:self.high-self.close}
    
one=StockA('one_dif',15,7)
print(one.dif())
two=StockA('two_dif',66,20)
print(two.dif())

{'one_dif': 8}
{'two_dif': 46}


# 3. pandas数据处理试题

3.1 如何查看列名、怎么对数据转置

用.columns可以查看列名，用.transpose()可以进行转置

3.2 读取data里的600029这只股票的DataFrame,将其收盘价转换成用Numpy的Array格式，并用talib计算10日EMA值，返回ndarray的最后五个值

In [4]:
import numpy as np
import pandas as pd
df=pd.read_excel('sz50.xlsx',sheetname='600029.XSHG',index_col='datetime').close

In [5]:
dff=df.values
print(type(dff))
import talib as ta
EMA=ta.EMA(dff,10)
print(EMA[-5:])

<class 'numpy.ndarray'>
[ 15.08227205  15.2564044   15.44433088  15.72172526  15.96322976]


3.3 读取sz50.xlsx的['600029.XSHG','600050.XSHG','601318.XSHG']的全数据做成Panel

In [6]:
import pandas as pd
sym=['600029.XSHG','600050.XSHG','601318.XSHG']
dict_df={}
for s in sym:
    df=pd.read_excel('sz50.xlsx',sheetname=s,index_col='datetime')
    dict_df[s]=df
PN=pd.Panel(dict_df)
PN

<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 215 (major_axis) x 5 (minor_axis)
Items axis: 600029.XSHG to 601318.XSHG
Major_axis axis: 2017-01-03 15:00:00 to 2017-11-20 15:00:00
Minor_axis axis: close to volume

3.4把Panel转成ndim为3的Numpy，然后用array的切片读取ndim为2的三只股票最近20天的收盘价

In [7]:
#接上题
print(PN.shape)
asd=PN.loc[:,:,'close']
print(asd.values[-20:].transpose())

(3, 215, 5)
[[  13.85   13.82   13.83   14.11   14.25   14.39   15.1    15.15   15.22
    14.97   14.89   14.99   14.71   15.07   15.35   16.     16.04   16.29
    16.97   17.05]
 [   8.53    8.56    8.62    8.88    9.25    9.24    9.43    9.25    9.02
     9.15    9.63    9.5     9.9     9.97    9.96    9.49    9.68    9.61
     9.63    9.8 ]
 [ 134.83  134.56  137.5   143.18  143.48  144.15  143.61  143.65  144.35
   143.36  146.41  144.71  148.56  156.53  157.12  157.72  154.99  163.52
   168.58  169.57]]


3.5 建立一个5*5的矩阵，值从0到24

In [8]:
import numpy as np
s=np.arange(25).reshape(5,5)
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
